import { rootFolder } from '#utils/constants';
import { LogLevel } from '@sapphire/framework';
import { setup } from '@skyra/env-utilities';
import { ClientOptions, Intents, Options } from 'discord.js';
import { join } from 'node:path';

setup(join(rootFolder, 'src', '.env'));

const { FLAGS } = Intents;

export const CLIENT_OPTIONS: ClientOptions = {
	disableMentionPrefix: false,
	defaultPrefix: '!?',
	intents: [FLAGS.GUILD_MESSAGES, FLAGS.GUILDS],
	makeCache: Options.cacheEverything(),
	loadDefaultErrorListeners: process.env.NODE_ENV !== 'production',
	logger: { level: process.env.NODE_ENV === 'production' ? LogLevel.Info : LogLevel.Debug },
	loadMessageCommandListeners: true,
	allowedMentions: { users: [], roles: [] },
	subcommandsAdvanced: { nameCommandsAutogenerated: true }
};
